### ISSUE TITLE
Use media keys for skipping to next video

### ISSUE THREAD

**Issue by kirbiyik** [edanchenkov/MenuTube#10]
Is it possible to implement this feature?

**Comment by edanchenkov** [comment]
Do you mean if you are listening playlist? I think it is an interesting feature and can be implemented. I don't know when, but I will try to work again on this project some time soonish. It requires some minor fixes and improvements. 

PR is very welcome!

**Comment by kirbiyik** [comment]
I mean youtube always assigns a video as next video when you listen/watch any video. In my scenario, I'd like to press the media button >> and start to listen next song. By the way thanks for this app I really liked it's simplicity. 
I'd love to make a PR but this is not a topic I have necessary skill set.

**Comment by edanchenkov** [comment]
I think this issue is now resolved in 1.6.1. And you should be able to use media keys for navigating in YouTube playlist. Other shortcuts have been changed, so check `Video controls` page from MenuTube's menu.
