### ISSUE TITLE
Install with Homebrew Cask

### ISSUE THREAD

**Issue by ran-dall** [edanchenkov/MenuTube#11]
@edanchenkov I made a `cask` to install MenuTube with Homebrew Cask 🍻.  
https://github.com/ran-dall/homebrew-repo/blob/master/Casks/menutube.rb

I didn't know if you were going to start working on it soon, so I didn't want to add it to Homebrew Cask yet; but when you do, I'd be happy to submit it for you. 👍

For now though if you want to install this with Homebrew Cask, you can just run.

```bash
brew cask install https://raw.githubusercontent.com/ran-dall/homebrew-repo/master/Casks/menutube.rb
```

**👌 Great work!**

**Comment by edanchenkov** [comment]
Wow, that looks great! Thank you. I didn't think about it, so feel free to continue and submit your cask.

**Comment by ran-dall** [comment]
@edanchenkov Are you planning on working on it soon? Maybe a new commit or two? I don't want the folk over at HBC to think it's `abandoned` or anything.

**Comment by edanchenkov** [comment]
I just pushed one commit to get rid of security alerts. Anyhow, I don't think it matters if we try to look like we are fiercely working on this app right now. Anybody can easily check commit history. MenuTube is not abandoned, but neither in active development.

**Comment by ran-dall** [comment]
https://github.com/Homebrew/homebrew-cask/pull/63023 -- I'll let you know once merged.

**Comment by edanchenkov** [comment]
Great, you can notify me with a PR to MenuTube's repo with updated Readme file including brew cask installation information.

**Comment by vitorgalvao** [comment]
HBC maintainer here.

I’ll merge this, but in a year’s time it may removed due to low number of downloads.
