### ISSUE TITLE
"This video requires payment to watch."

### ISSUE THREAD

**Issue by NorthIsUp** [edanchenkov/MenuTube#14]
When trying to watch https://www.youtube.com/watch?v=hHW1oY26kxQ&feature=youtu.be i'm getting an error about payments.

![image](https://user-images.githubusercontent.com/122612/59066467-fc724d80-8863-11e9-87ab-f0b02b3b7d74.png)

**Comment by NorthIsUp** [comment]
this only happens on mobile view, the stream works on desktop.

**Comment by edanchenkov** [comment]
Yes, I believe it has something to do with new YouTube policy regarding background playback on mobile devices. There is no simple solution for this issue, however I will try to look into it at some point.

For how many videos have you seen similar issue?

**Comment by NorthIsUp** [comment]
so far it has happened on every live stream

**Comment by edanchenkov** [comment]
@NorthIsUp Fixed. See 1.5.0 https://github.com/edanchenkov/MenuTube/releases/tag/1.5.0
