### ISSUE TITLE
Desktop view is not working

### ISSUE THREAD

**Issue by ran-dall** [edanchenkov/MenuTube#15]
For the last few weeks, I've been having issues loading the Desktop view, however, the Mobile view still works. I've attached a screenshot...

![Screen Shot 2019-09-07 at 5 50 37 PM](https://user-images.githubusercontent.com/17261190/64481775-42f38300-d198-11e9-9ae0-47e4687eb27f.png)

**Comment by edanchenkov** [comment]
Hey, yes it seems like something has change on YouTube side. The first thing we should try to do as well is to update electron and build tools. This might help. Though I am not sure when I have time to look into it.

**Comment by ran-dall** [comment]
@edanchenkov Sound good. If I get I chance, I'll tinker with it in the next week...

**Comment by edanchenkov** [comment]
@ran-dall good, I'd appreciate this. Let me know if I can help with something.

**Comment by edanchenkov** [comment]
@ran-dall Fixed. See 1.5.0 https://github.com/edanchenkov/MenuTube/releases/tag/1.5.0
