### ISSUE TITLE
No code signature in version 1.7.4?

### ISSUE THREAD

**Issue by suschizu** [edanchenkov/MenuTube#27]
Hello!
I've received a notification that the code signature is missing in the latest download 

EXPECTED Red Nuclear Monkey Oy (6N2WC87M54)

can you confirm this? 

```
codesign -v /Volumes/MenuTube\ 1.7.4/MenuTube.app 
/MenuTube 1.7.4/MenuTube.app: code object is not signed at all
```

**Comment by edanchenkov** [comment]
Yes, this apple dev account has expired, I might renew it later. Sorry for this inconvenience.

**Comment by suschizu** [comment]
great - thanks for the confirmation @edanchenkov <3
