### ISSUE TITLE
MenuTube blank screen

### ISSUE THREAD

**Issue by PxBCPG** [edanchenkov/MenuTube#35]
Hi!
Since very recently I can't use MenuTube anymore on my Mac. 
I only have a blank screen. 
I can reach YouTube from an external browser but menu tube doesn't work anymore. 
So sad since it's a very good app :(

**Comment by edanchenkov** [comment]
Hello!

Thanks for reaching out and kind words. 

Do you use [the latest version of menutube](https://github.com/edanchenkov/MenuTube/releases/tag/1.7.4)? I cannot reproduce behaviour you described in MunuTube 1.7.4.

In any case I would suggest to reinstall / install the latest version of the app and see if it helps.

![Screenshot 2023-04-18 at 09 03 58](https://user-images.githubusercontent.com/2707765/232686026-b0ab8962-a235-4ba3-b153-504cf392ff12.png)

**Comment by PxBCPG** [comment]
Hi! 
Thanks for you kind answer. 
Unfortunately, I'm running the latest version of MenuTube (1.7.4).
I am on macOS Big Sur if that can help. 

The real question is that it worked perfectly well not so long ago and suddenly only a white screen...

<img width="492" alt="Screen Shot 2023-04-18 at 08 37 23" src="https://user-images.githubusercontent.com/74296895/232692111-79134b50-f547-4923-badc-d3d23d912e61.png">
<img width="500" alt="Screen Shot 2023-04-18 at 08 37 30" src="https://user-images.githubusercontent.com/74296895/232692121-5e29eb8b-e36a-4e85-baac-c0c5408c8848.png">

**Comment by PxBCPG** [comment]
Alright so apparently I found an older version that still work. 
But the newest one doesn't. 
Version 1.7.3 work on my Mac

**Comment by edanchenkov** [comment]
Hmm interesting, have you tried to install 1.7.4 again?

I tried it on Ventura 13.3.1, maybe there is something about macOs version.

**Comment by PxBCPG** [comment]
Yes I don't know why but it just won't work. Anyways I'm still happy with the previous version ;)
Thank you very much for your time and support!
