### ISSUE TITLE
No longer works in the background

### ISSUE THREAD

**Issue by thomas-alrek** [edanchenkov/MenuTube#6]
When a video is playing, I am unable to hide the window of MenuTube without causing the video to pause.

If i press the tray icon, it hides the window, but the video also gets paused.

Tested on macOS Sierra 10.12.4

**Comment by edanchenkov** [comment]
Uhh, tough one. I am aware of this. To fix it, remove everything from your cache folder and try again. I guess I must release a fix for this...

```

**Comment by thomas-alrek** [comment]
@edanchenkov the Cache folder is ~ 231 MB.

I do not currently get warnings about free HDD space, and have approximate 20 GB free at this moment.

I did clean the Cache folder, and restart MenuTube. But unfortunately, that didn't seem to resolve the issue.

Could it be that YouTube is doing something clever and actively pausing it when in the background? Or would that be impossible for it to detect?

**Comment by edanchenkov** [comment]
Hmm, ok. 231 MB isn't much, however 20 GB of free space might tell macOS sierra to do some shady stuff.

Youtube can well do that. Which user-agent do use set in preferences btw? Changing it to Android or Desktop might help as well. Please try this. 

I failed to detect exact the issue, my best guess was cache, then user agent. I did both and both helped in different times. However changing user agent is not really a solution at all. I can not ask user to do that every time 😄 .

**Comment by thomas-alrek** [comment]
I had my user-agent set to iPad. I switched it to Android, and this seems to have resolved the issue. Thanks for the tip!

Maybe the iPad option should be removed? Seems like they do something specific there to enforce the pause when in background.

**Comment by edanchenkov** [comment]
@thomas-alrek that's great! Yes, I guess somehow YouTube paused video when maybe focus is lost. I need to check this. Thanks for your input!

**Comment by edanchenkov** [comment]
@thomas-alrek I just tried the latest MenuTube version and iPad works for me...

**Comment by thomas-alrek** [comment]
Huh, that's weird. Is there any way for me to open the devtools within the app?

**Comment by edanchenkov** [comment]
Not in your build. Which version of MenuTube you are using? You can find it in preferences page at the bottom.

Could you tell me size of the following folders again?

```
du -hs ~/Library/Application\ Support/menutube/Cache &&
du -hs ~/Library/Caches/menutube &&
du -hs ~/Library/Saved\ Application\ State/com.electron.menutube.savedState
```

I am going to spend some time this weekend to fix that error.

**Comment by edanchenkov** [comment]
@thomas-alrek ok, seems like ios doesn't want us to run YouTube at all in background. So I remove these options, now there is only Android user-agent and user cannot choose. 

Closing the issue. 

https://github.com/edanchenkov/MenuTube/releases/tag/1.2.3
