### ISSUE TITLE
Not working for live videos

### ISSUE THREAD

**Issue by aleufms** [edanchenkov/MenuTube#7]
It's not working for live videos. Example: https://www.youtube.com/watch?v=heQY7SEjdmE

**Comment by edanchenkov** [comment]
@aleufms thank you for reporting this. I ll look into the issue during weekends. Let's see if there is something we can do about it...

**Comment by edanchenkov** [comment]
Live stream is broken even in the latest chrome browser, if you enter device emulation mode. I am afraid there is nothing that we can do easily...

**Comment by edanchenkov** [comment]
Apparently chaning userAgent to desktop would help

**Comment by edanchenkov** [comment]
@aleufms hey, awesome news! it is working now in the latest version. Enjoy! :)
