### ISSUE TITLE
Paste does not work

### ISSUE THREAD

**Issue by andreax79** [edanchenkov/MenuTube#8]
Unable to paste a text in the search bar on macOS 10.12.4

**Comment by edanchenkov** [comment]
@andreax79 You could find new release https://edanchenkov.github.io/MenuTube/, that should not have this issue. Thank you for reporting, let me know if there is still a problem or other issues.

**Comment by andreax79** [comment]
Thanks, it works perfectly. By the way, this is a really cool project !

**Comment by edanchenkov** [comment]
Awesome, I'm glad you like it. Spread the word! :)
