### ISSUE TITLE
Pop-Out Video Window Like MacOS's PIP Feature

### ISSUE THREAD

**Issue by fatihturan** [edanchenkov/MenuTube#9]
Can you add a PIP feature to MenuTube like [MacOS's PIP feature](https://cl.ly/o1Nh)?

**Comment by edanchenkov** [comment]
@fatihturan I'll try to look at it at some point, however I don't think this will work in a webview, since it only works in safari browser on mac. Meanwhile you can move and resize the window just like PIP. In preferences you can find `WINDOW DRAGGABLE` and `WINDOW RESIZE`.

**Comment by fatihturan** [comment]
It would be great if you could do it in some way. :)

Also I enabled the Window Draggable option but I can't move the window from the bar of the top or something else. How do you move the window?

**Comment by edanchenkov** [comment]
@fatihturan there can be a bug actually :) You should resize the window a bit and then it becomes draggable, sorry about that ;)

**Comment by fatihturan** [comment]
Oh, there is definitely a bug. :) Anyway, at least I am able to move the window.

By the way, if you can hide top and bottom bars when move mouse outside and show bars again when mouse enter window the end result is exactly what I want.

**Comment by edanchenkov** [comment]
@fatihturan Just released 1.3.0 with PIP feature (custom, not macOS native)  + fix bug when you were unable to drag the window. Thanks for feedback!

**Comment by fatihturan** [comment]
It's pretty good news. :) But I have some minor issues about this feature:

1. When in PIP mode, status bar icon become [active mode (blue color) ](https://cl.ly/oCpW). Can you remove the active mode on status bar icon when moved out the window? It's little bit annoying. :)
2. I can drag out the window from top into somewhere. But if I click on status bar icon for temporary hiding window and again click on status bar icon [PIP window going on top again](https://cl.ly/oEAM).
3. Can you move the [top bar](https://cl.ly/oDCZ) on top of video and player controls on bottom of video as overlay? They bars are take up a lot of space especially in [PIP mode](https://cl.ly/oDdh).

Thank you.

**Comment by edanchenkov** [comment]
1. and 2.  With new update
3. There is no easy way to move video controls around. Position of top bar is a matter of user preference, and should be optional. If we get more requests for that I ll might do it, otherwise feel fee to do changes yourself and PR, or let's wait until someone else take care of it :) You can create a new ticket for this.

**Comment by fatihturan** [comment]
Thank you for your interest and efforts! :) 👏

**Comment by edanchenkov** [comment]
Thank you for the feedback and feature requests, those were nice to have for a long time. I am glad to see other people use MenuTube. Spreding the word about the app is very appriciated 🥇
